version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    ignore:
      - update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
