language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - 1.13.0
  - 1.22.0
  - stable
  - beta
  - nightly
script:
  - cd enum-map
  - cargo test --verbose
  - cargo test --verbose --all-features
after_success: |
  bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  cargo tarpaulin --features serde --out Xml
  bash <(curl -s https://codecov.io/bash)
