# SPDX-FileCopyrightText: 2023 - 2025 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: pull_request
  - event: push
    branch:
      - master

steps:
  lint:
    depends_on: []
    image: fsfe/reuse:3.0.2@sha256:985ca841881779fa56560cd8478821270e78e4f23e21d7d741370a4abba3c654
    commands:
      - reuse lint
  miri:
    depends_on: []
    image: instrumentisto/rust:nightly-2025-02-26@sha256:786a8a9b058e86a7d1f57fd5af81f9b54e00d1d6b65f0588c23375aaca86fa43
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup component add miri
      - cargo miri test --all-features --locked --verbose
  rustfmt:
    depends_on: []
    image: rust:1.85.0@sha256:caa4a0e7bd1fe2e648caf3d904bc54c3bfcae9e74b4df2eb9ebe558c9e9e88c5
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
  test-stable: &rust
    depends_on: []
    image: rust:1.85.0@sha256:caa4a0e7bd1fe2e648caf3d904bc54c3bfcae9e74b4df2eb9ebe558c9e9e88c5
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - cargo build --all-features --locked --verbose
      - cargo test --no-default-features --locked --verbose
      - cargo test --all-features --locked --verbose
  test-msrv:
    <<: *rust
    # Update Cargo.toml and renovate.json when updating this.
    image: rust:1.81.0@sha256:cae43437babe4a513bfaf1ebaed7b47e916e1a96bea4496ee763708f2a2b5bdb
