# SPDX-FileCopyrightText: 2023 - 2025 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: pull_request
  - event: push
    branch:
      - master

steps:
  lint:
    depends_on: []
    image: fsfe/reuse:3.0.2@sha256:985ca841881779fa56560cd8478821270e78e4f23e21d7d741370a4abba3c654
    commands:
      - reuse lint
  miri:
    depends_on: []
    image: instrumentisto/rust:nightly-2024-03-19@sha256:655a9cc22eb4143a679d893f38dbea03bb57cd0d27fa90fc5c3d3106a14a812e
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup component add miri
      - cargo miri test --all-features --locked --verbose
  rustfmt:
    depends_on: []
    image: rust:1.77.0@sha256:00e330d2e2cdada2b75e9517c8359df208b3c880c5e34cb802c120083d50af35
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
  test-stable: &rust
    depends_on: []
    image: rust:1.77.0@sha256:00e330d2e2cdada2b75e9517c8359df208b3c880c5e34cb802c120083d50af35
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - cargo build --all-features --locked --verbose
      - cargo test --no-default-features --locked --verbose
      - cargo test --all-features --locked --verbose
  test-msrv:
    <<: *rust
    # Update Cargo.toml and renovate.json when updating this.
    image: rust:1.66.1@sha256:23b7815cff2b70148cc7fa732825a5384a347b38217f162525c8f86610a6ae35
