# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: pull_request
  - event: push
    branch:
      - master

steps:
  lint:
    group: test
    image: fsfe/reuse:3.0.1@sha256:f8f4851e199f44a0e827ea7d248228e2045e26750707e4f5f1b5875caf4ac51a
    commands:
      - reuse lint
  miri:
    group: test
    image: instrumentisto/rust:nightly-2024-01-05@sha256:f3fc26b5bc76c76297f19c286bd23ac58fa283eb07a668c9be735b0d5246aa3b
    environment:
      - CARGO_TERM_COLOR=always
    commands:
      - rustup component add miri
      - cargo miri test --all-features --locked --verbose
  rustfmt:
    group: test
    image: rust:1.75.0@sha256:87f3b2f93b82995443a1a558c234212dafe79cfdc3af956539610560369ddcd0
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
  test-stable: &rust
    group: test
    image: rust:1.75.0@sha256:87f3b2f93b82995443a1a558c234212dafe79cfdc3af956539610560369ddcd0
    environment:
      - CARGO_TERM_COLOR=always
    commands:
      - cargo build --all-features --locked --verbose
      - cargo test --no-default-features --locked --verbose
      - cargo test --all-features --locked --verbose
  test-msrv:
    <<: *rust
    # Update Cargo.toml and renovate.json when updating this.
    image: rust:1.66.1@sha256:f72949bcf1daf8954c0e0ed8b7e10ac4c641608f6aa5f0ef7c172c49f35bd9b5
