[package]
name = "enum-map"
version = "0.2.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
repository = "https://github.com/xfix/enum-map"
license = "MIT/Apache-2.0"
description = "A library providing enum map providing type safe enum array"
keywords = ["data-structure", "no_std", "enum"]
categories = ["data-structures", "no-std"]

[badges]
travis-ci = { repository = "xfix/enum-map" }

[dependencies]
serde = { version = "1.0.0", optional = true, features = ["derive"] }

[dev-dependencies]
enum-map-derive = { version = "0.2.0", path = "../enum-map-derive" }
serde_test = "1.0.5"
serde_json = "1.0.2"
