[package]
name = "enum-map"
version = "0.2.14"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
repository = "https://github.com/xfix/enum-map"
license = "MIT/Apache-2.0"
description = "A library providing enum map providing type safe enum array"
keywords = ["data-structure", "no_std", "enum"]
categories = ["data-structures", "no-std"]
documentation = "https://docs.rs/enum-map"
readme = "README.md"

[badges]
travis-ci = { repository = "xfix/enum-map" }

[dependencies]
array-macro = "0.1.1"
serde = { version = "1.0.0", optional = true, features = ["derive"] }
enum-map-derive = { version = "0.2.0", path = "../enum-map-derive" }

[dev-dependencies]
serde_test = "1.0.5"
serde_json = "1.0.2"

[package.metadata.docs.rs]
features = ["serde"]
