[package]
name = "enum-map-derive"
version = "0.4.3"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
repository = "https://gitlab.com/KonradBorowski/enum-map"
license = "MIT/Apache-2.0"
description = "Macros 1.1 implementation of #[derive(Enum)]"
keywords = ["data-structure", "no_std", "enum"]
categories = ["data-structures", "no-std"]

[badges]
gitlab = { repository = "KonradBorowski/enum-map" }
maintenance = { status = "actively-developed" }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.0"
quote = "1.0.0"
syn = "1.0.1"

[dev-dependencies]
enum-map = "0.5.0"
