[package]
name = "enum-map-derive"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
repository = "https://github.com/xfix/enum-map"
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
