[package]
name = "enum-map-derive"
version = "0.1.3"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
repository = "https://github.com/xfix/enum-map"
license = "MIT/Apache-2.0"
description = "Macros 1.1 implementation of #[derive(EnumMap)]"
keywords = ["data-structure", "no_std", "enum"]
categories = ["data-structures", "no-std"]

[badges]
travis-ci = { repository = "xfix/enum-map" }

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
