# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: pull_request
  - event: push
    branch:
       - master

steps:
  miri:
    image: instrumentisto/rust:nightly-2023-11-29@sha256:cf2f72982c78e082d527dfd5b29219fc945132e1ffa7fd5c91774a000dec00b3
    environment:
      - CARGO_TERM_COLOR=always
    commands:
      - rustup component add miri
      - cargo miri test --all-features --locked --verbose
