# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: pull_request
  - event: push
    branch:
       - master

steps:
  miri:
    image: instrumentisto/rust:nightly-2023-10-30@sha256:df4b29a42df8334407bacfc0241c43f2263f3159f96b263a86038296c2406ba6
    environment:
      - CARGO_TERM_COLOR=always
    commands:
      - rustup component add miri
      - cargo miri test --all-features --locked --verbose
