# SPDX-FileCopyrightText: 2023 Konrad Borowski <konrad@borowski.pw>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

when:
  - event: pull_request
  - event: push
    branch:
       - master

matrix:
  RUST_IMAGE:
    - rust
    - "rust:1.65"

steps:
  test:
    image: ${RUST_IMAGE}
    environment:
      - CARGO_TERM_COLOR=always
    commands:
      - cargo build --all-features --locked --verbose
      - cargo test --no-default-features --locked --verbose
      - cargo test --all-features --locked --verbose
