# SPDX-FileCopyrightText: 2022 Konrad Borowski <konrad@borowski.pw>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

name: Dependency Review
on: [pull_request]
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v3
